version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'tub' 
      MYSQL_USER: '${MYSQLUSER}' # So you don't have to use root, but you can if you like
      MYSQL_PASSWORD: '${MYSQLPASSWORD}' #You can use whatever password you like
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}' #Password for root access
    ports:
      - '3306:3306'
    expose: # Opens port 3306 on the container
      - '3306'
    volumes: # Where our data will be persisted
      - tub:/var/lib/mysql
      #- bd/tub.sql:/bd/import/bd.sql
    command: 
      #- 'mysql -u root -p tub'
      #- 'CREATE DATABASE tub;'
      #- 'USE tub;'
      #- 'SOURCE /bd/import/bd.sql;'

volumes:
  tub:
    driver: local